[package]
name = "eigen"
version = "5.0.0"

[targets.eigen]
kind = "lib"

[build]
include_dirs = [".", "blas"]
sources = [
    "blas/single.cpp",
    "blas/double.cpp",
    "blas/complex_single.cpp",
    "blas/complex_double.cpp",
    "blas/xerbla.cpp",
    "blas/f2c/srotm.c",
    "blas/f2c/srotmg.c",
    "blas/f2c/drotm.c",
    "blas/f2c/drotmg.c",
    "blas/f2c/lsame.c",
    "blas/f2c/dspmv.c",
    "blas/f2c/ssbmv.c",
    "blas/f2c/chbmv.c",
    "blas/f2c/sspmv.c",
    "blas/f2c/zhbmv.c",
    "blas/f2c/chpmv.c",
    "blas/f2c/dsbmv.c",
    "blas/f2c/zhpmv.c",
    "blas/f2c/dtbmv.c",
    "blas/f2c/stbmv.c",
    "blas/f2c/ctbmv.c",
    "blas/f2c/ztbmv.c",
    "blas/f2c/complexdots.c",
]
[features]
default = []
blas = []
